library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity sevseg_disp is
    Port ( 
        VAL : in STD_LOGIC_VECTOR (3 downto 0); -- adder sum
        AN_SEL : in std_logic_vector(2 downto 0); -- numbered anode select (Selected via clock)
        AN : out std_logic_vector(7 downto 0); -- per bit which anode to turn on/off
        SEG : out STD_LOGIC_VECTOR (7 downto 0) -- 7-1 bits are cathodes, 0 bit is dot. 0 on, 1 off
    );
end sevseg_disp;

architecture Behavioral of sevseg_disp is
    
    --ANDODE DECODER
	component AnnodeDecoder
	   Port (X: in std_logic_vector(2 downto 0); -- b bits "000" digCODE generated by clkDiv
		    AN_o: out std_logic_vector(7 downto 0)); --8 bits to select the annode to display on 
	end component;
	
	--7 SEG ENCODER to display on 7 SEG
	component sevseg_dot
	Port (  
            int  : in std_logic_vector (4 downto 1);--same input vector here
			dot : in std_logic;		--as here when using component. 4-1 bits are character in hex, 0 bit is dot
            seg : out std_logic_vector (7 downto 0)
        );-- 6-0 bits are cathodes, 7 bit is dot. -- 0 is dot on, 1 is dot off
	end component;
	
begin
    
    --AnnodeDecoder/Select annode
	AC: AnnodeDecoder 
	   port map(
	       X => AN_SEL, 
	       AN_o => AN
       );
	-- Cathode Decoder/ Select LEDs
	CathCoder: sevseg_dot 
	    port map (
            int => VAL,
            dot => '1',
            seg => SEG
		);
end Behavioral;
