library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
--	In-Datapath-Out: 
--      Switches for ALU input and Cin + CLK for 7seg selection =>
--      Clock divider => 
--      4-bit ALU =>
--      Anode decoder =>
--      7seg Cathode Mux => 
--      7seg decoder =>
--      7seg anode + cathode output

entity main is
    Port (	CLK100MHZ: in std_logic;
			SW: in std_logic_vector(11 downto 0); -- use 12 switches as binary bits
			ANODES : out std_logic_vector(7 downto 0); -- 7 seg ANODES
			SEG_CATHODES : out std_logic_vector(7 downto 0) -- 7 seg Cathodes
	);
end main;

architecture Structural of main is

	--Component Declarations:

    -- 4-bit ALU
    component four_bit_alu
        Port ( 
            A, B   : in  std_logic_vector(3 downto 0);
            Op     : in  std_logic_vector(1 downto 0);
            Cin    : in std_logic;
            Carry  : out std_logic;
            Res : out std_logic_vector(3 downto 0)
        );
    end component;

	--ANDODE DECODER
	component AnnodeDecoder
	   Port (X: in std_logic_vector(2 downto 0); -- b bits "000" digCODE generated by clkDiv
		    AN_o: out std_logic_vector(7 downto 0)); --8 bits to select the annode to display on 
	end component;

	component Mux8To1_8bit
		Port (	
			I_0, I_1, I_2, I_3, I_4, I_5, I_6, I_7 : in std_logic_vector(7 downto 0);
			S : in  std_logic_vector(2 downto 0);
			Z : out  std_logic_vector(7 downto 0)
		);
	end component;
	
	--7 SEG ENCODER to display on 7 SEG
	component sevseg_dot
	Port (  
            int  : in std_logic_vector (4 downto 1);--same input vector here
			dot : in std_logic;		--as here when using component. 4-1 bits are character in hex, 0 bit is dot
            seg : out std_logic_vector (7 downto 0)
        );-- 6-0 bits are cathodes, 7 bit is dot. -- 0 is dot on, 1 is dot off
	end component;
    
    -- Seven segment display logic
    component sevseg_disp
        Port (
            I_0, I_1, I_2, I_3, I_4, I_5, I_6, I_7 : in STD_LOGIC_VECTOR (3 downto 0);
            AN_SEL : in std_logic_vector(2 downto 0);
            AN : out std_logic_vector(7 downto 0);
            SEG : out STD_LOGIC_VECTOR (7 downto 0)
        );
    end component;

    -- Signals
    signal clkdiv : std_logic_vector(10 downto 0); -- CLOCK 
    signal digCode : std_logic_vector (2 downto 0); --signal from clock division for anode and cathode selection
	-- Signals for 4-bit ALU
    signal sw_to_a, sw_to_b, res : std_logic_vector(3 downto 0);
    signal carry: std_logic;
begin
	clock_divider: process (CLK100MHz)		-- create system clock divder
	begin
		if (rising_edge(CLK100MHz)) then
			clkdiv <= clkdiv+1;
		end if;
	end process clock_divider;
	
	digit_select: process (clkdiv(10))
	begin
		if (rising_edge(clkdiv(10))) then
			case digCode is				--used to rotate 7 seg digits
		 		when "000" => digCode <= "001";
				when "001" => digCode <= "010";
				when "010" => digCode <= "011";
				when "011" => digCode <= "100";
				when "100" => digCode <= "101";
				when "101" => digCode <= "110";
				when "110" => digCode <= "111";
				when "111" => digCode <= "000";
			end case;
		end if;
	end process digit_select;

	sw_to_a <= SW(7 downto 4);
	sw_to_b <= SW(3 downto 0);
	alu: four_bit_alu
	    port map(
            A => sw_to_a,
            B => sw_to_b,
            Op => SW(10 downto 8),
            Carry => carry,
            Sum => res
        );

	--AnnodeDecoder/Select annode
	AC: AnnodeDecoder 
	   port map(
	       X => AN_SEL, 
	       AN_o => ANODES
       );
	Cathode_mux: Mux8To1_8bit
		port map(
			I_0 => res,
            I_1 => sw_to_b,
            I_2 => sw_to_a,
            I_3 => "",
            I_4 => "",
            I_5 => "",
            I_6 => "",
            I_7 => "",
			S => digCode,
			Z => VAL
		);
	-- Cathode Decoder/ Select LEDs
	CathCoder: sevseg_dot 
	    port map (
            int => VAL,
            dot => '1',
            seg => SEG_CATHODES
		);
	

end Structural;
