library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity sevseg_disp is
    Port (
        I_0, I_1, I_2, I_3, I_4, I_5, I_6, I_7 : in std_logic_vector(3 downto 0);
        DOT : in std_logic;
        AN_SEL : in std_logic_vector(2 downto 0); -- numbered anode select (Selected via clock)
        AN : out std_logic_vector(7 downto 0); -- per bit which anode to turn on/off
        SEG : out STD_LOGIC_VECTOR (7 downto 0) -- 7-1 bits are cathodes, 0 bit is dot. 0 on, 1 off
    );
end sevseg_disp;

architecture Behavioral of sevseg_disp is
    
    -- ANODE DECODER
	component AnnodeDecoder
	   Port (X: in std_logic_vector(2 downto 0); -- b bits "000" digCODE generated by clkDiv
		    AN_o: out std_logic_vector(7 downto 0)); --8 bits to select the annode to display on 
	end component;
	-- Cathode MUX
	component Mux8To1_4bit
		Port (	
			I_0, I_1, I_2, I_3, I_4, I_5, I_6, I_7 : in std_logic_vector(3 downto 0);
			S : in  std_logic_vector(2 downto 0);
			Z : out  std_logic_vector(3 downto 0)
		);
	end component;
	--7 SEG ENCODER to display on 7 SEG
	component sevseg_dot
	Port (  
            int  : in std_logic_vector (4 downto 1);--same input vector here
			dot : in std_logic;
            seg : out std_logic_vector (7 downto 0) -- 6-0 bits are cathodes, 7 bit is dot. -- 0 is dot on, 1 is dot off
        );
	end component;
	
    signal VAL : std_logic_vector(3 downto 0); -- output of cathode MUX to input of 7 SEG encoder
begin
    -- AnnodeDecoder/Select annode
	AC: AnnodeDecoder
	   port map(
	       X => AN_SEL, 
	       AN_o => AN
       	);
    -- Cathode Mux
	Cathode_mux: Mux8To1_4bit
		port map(
			I_0 => I_0,
            I_1 => I_1,
            I_2 => I_2,
            I_3 => I_3,
            I_4 => I_4,
            I_5 => I_5,
            I_6 => I_6,
            I_7 => I_7,
			S => AN_SEL,
			Z => VAL
		);
	-- Cathode Decoder / Select LEDs
	CathCoder: sevseg_dot 
	    port map (
            int => VAL,
            dot => '1',
            seg => SEG
		);
end Behavioral;
